apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mod-example
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: testapp
  url: oci://registry.fi.intel.com/xiangdai/envoy-modsecurity-wasm-plugin:0.1.0
  imagePullPolicy: Always
  pluginConfig:
    "rules_service": rule-service
    "duration_time": "30"
