# permissions for end users to view rules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rule-viewer-role
rules:
- apiGroups:
  - modsecurity.intel.com
  resources:
  - rules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - modsecurity.intel.com
  resources:
  - rules/status
  verbs:
  - get
